In [1]:
import torch

In [12]:
test=torch.BoolTensor(2,2)
test

tensor([[False, False],
        [False, False]])

In [20]:
test2=torch.BoolTensor(2,2)
test2[:]=True
test2[1,1]=False
test2

tensor([[ True,  True],
        [ True, False]])

In [21]:
test+test2

tensor([[ True,  True],
        [ True, False]])

In [24]:
test=torch.Tensor(3,3)
test

tensor([[-3.7177e-25,  4.5762e-41, -3.7177e-25],
        [ 4.5762e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [25]:
test>0

tensor([[False,  True, False],
        [ True, False, False],
        [False, False, False]])

In [37]:
test=torch.tensor([[1,1,1,],[2,2,2],[3,3,3]])
test

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [41]:
test2=torch.tensor([[1,1,1,],[2,2,2],[3,3,3]])
test*test2

tensor([[1, 1, 1],
        [4, 4, 4],
        [9, 9, 9]])

In [36]:
torch.dot(test,test2)

RuntimeError: 1D tensors expected, but got 2D and 1D tensors

In [1]:
274-27

247